name: CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lints:
    runs-on: ubuntu-latest
    steps:
      - name: Get prereqs
        run: sudo apt-get install protobuf-compiler
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt, clippy
          target: wasm32-unknown-unknown
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path esp32/wasm-hub/Cargo.toml  --all -- --check
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path esp32/wasm-hub/Cargo.toml --target wasm32-unknown-unknown -- -D warnings
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path esp32/wasm-hub/Cargo.toml --release --target wasm32-unknown-unknown -- -D warnings
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Get prereqs
      run: sudo apt-get install protobuf-compiler
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: actions-rs/cargo@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - name: Test regular
      run: cargo test --manifest-path esp32/wasm-hub/Cargo.toml --all
