name: CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lints:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path esp32/wasm-hub/Cargo.toml  --all -- --check
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path esp32/wasm-hub/Cargo.toml --target wasm32-unknown-unknown -- -D warnings
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path esp32/wasm-hub/Cargo.toml --release --target wasm32-unknown-unknown -- -D warnings
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/cargo@v1
    - uses: actions-rs/toolchain@v1
    - name: Test regular
      run: cargo test --manifest-path esp32/wasm-hub/Cargo.toml --all
