name: push
on: [push]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Build docker images
        run: docker build -t firmware-builder .
      - name: Create output directory
        run: mkdir /tmp/out; pwd; ls -lha
      - name: Run docker builder
        run: docker run -t --rm  -v /tmp/out:/out:Z -v ${PWD}:/src:Z firmware-builder
